<?php
// auto-generated by sfPropelAdmin
// date: 2007/02/14 16:46:15
?>
<?php use_helper('I18N', 'Date') ?>
<div id="sf_admin_container">

<h1><?php echo __(' ',
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('alumno/list_header', array('filters' => $filters)) ?>
</div>

<div id="sf_admin_bar">

<?php echo include_partial('filters', array('filters' => $filters)) ?>

</div>
<div id="sf_admin_content">

<?php if(!$pager->getNbResults()): ?>
<?php echo __('no result') ?>
<?php else: ?>
<table cellspacing="0" class="sf_admin_list">
<thead>
<tr>
<?php echo include_partial('list_th_tabular') ?>
  <th id="sf_admin_list_th_sf_actions"><?php echo __('Actions') ?></th>
</tr>
</thead>
<tbody>
<?php $i = 1; foreach ($pager->getResults() as $alumno): $odd = fmod(++$i, 2) ?>
<tr class="sf_admin_row_<?php echo $odd ?>">
<?php echo include_partial('list_td_tabular', array('alumno' => $alumno)) ?>
<?php echo include_partial('list_td_actions', array('alumno' => $alumno)) ?>
</tr>
<?php endforeach; ?>
</tbody>
<tfoot>
<tr><th colspan="10">
<div class="float-right">
<?php if ($pager->haveToPaginate()): ?>
  <?php echo link_to(image_tag(sfConfig::get('sf_admin_web_dir').'/images/first.png', 'align=absmiddle'), 'alumno/list?page=1') ?>
  <?php echo link_to(image_tag(sfConfig::get('sf_admin_web_dir').'/images/previous.png', 'align=absmiddle'), 'alumno/list?page='.$pager->getPreviousPage()) ?>

  <?php foreach ($pager->getLinks() as $page): ?>
    <?php echo link_to_unless($page == $pager->getPage(), $page, 'alumno/list?page='.$page) ?>
  <?php endforeach; ?>

  <?php echo link_to(image_tag(sfConfig::get('sf_admin_web_dir').'/images/next.png', 'align=absmiddle'), 'alumno/list?page='.$pager->getNextPage()) ?>
  <?php echo link_to(image_tag(sfConfig::get('sf_admin_web_dir').'/images/last.png', 'align=absmiddle'), 'alumno/list?page='.$pager->getLastPage()) ?>
<?php endif; ?>
</div>
<?php echo format_number_choice('[0] no result|[1] 1 result|(1,+Inf] %1% results', array('%1%' => $pager->getNbResults()), $pager->getNbResults()) ?>
</th></tr>
</tfoot>
</table>
<?php endif; ?>

<?php echo include_partial('list_actions') ?>

</div>

<div id="sf_admin_footer">
<?php include_partial('alumno/list_footer') ?>
</div>
</div>
