<?php
// auto-generated by sfPropelAdmin
// date: 2007/08/06 12:32:12
?>
    <td><?php echo $rel_anio_actividad->getAnio() ?></td>
      <td><?php echo $rel_anio_actividad->getActividad() ?></td>
      <td><?php echo $rel_anio_actividad->getOrientacion() ?></td>      
      <td><?php echo $rel_anio_actividad->getHoras() ?></td>
