<?php
// auto-generated by sfPropelAdmin
// date: 2007/07/18 17:55:34
?>
<?php if ($sf_request->getError('delete')): ?>
<div class="form-errors">
  <h2>Could not delete the selected Horarioescolar</h2>
  <ul>
    <li><?php echo $sf_request->getError('delete') ?></li>
  </ul>
</div>
<?php endif; ?>
