<?php
// auto-generated by sfPropelAdmin
// date: 2007/07/18 17:55:34
?>
    <td><?php echo link_to($horarioescolar->getNombre() ? $horarioescolar->getNombre() : __('-'), 'horarioescolar/edit?id='.$horarioescolar->getId()) ?></td>
    <td><?php echo $horarioescolar->getDescripcion() ?></td>
    <td><?php echo ($horarioescolar->getEvento())?$horarioescolar->getEvento()->getInfoEnTexto():"";?></td>
    <td><?php echo get_partial('fk_horarioescolartipo_id', array('type' => 'list', 'horarioescolar' => $horarioescolar)) ?></td>
    <td><?php echo get_partial('fk_establecimiento_id', array('type' => 'list', 'horarioescolar' => $horarioescolar)) ?></td>
    <td><?php echo get_partial('turnos_list', array('type' => 'list', 'horarioescolar' => $horarioescolar)) ?></td>
  