<?php
// auto-generated by sfPropelAdmin
// date: 2007/07/18 17:55:34
?>
<ul class="sf_admin_actions">
      <li><?php echo button_to(__('create'), 'horarioescolar/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>
      <li><?php echo button_to(__('Ver Calendario'), 'horarioescolar/verCalendario', array (
  'style' => 'background: #ffc url(/sf/sf_admin/images/default_icon.png) no-repeat 3px 2px',
)) ?></li>
  </ul>
