<?php
// auto-generated by sfPropelAdmin
// date: 2007/02/16 11:42:06
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('list'), 'relCalendariovacunacionAlumno/list?filters%5Bfk_alumno_id%5D='.$rel_calendariovacunacion_alumno->getFkAlumnoId().'&filter=filter', array (
  'class' => 'sf_admin_action_list',
)) ?></li>
  <li><?php echo submit_tag(__('save and add'), array (
  'name' => 'save_and_add',
  'class' => 'sf_admin_action_save_and_add',
)) ?></li>
  <li><?php echo submit_tag(__('save'), array (
  'name' => 'save',
  'class' => 'sf_admin_action_save',
)) ?></li>
</ul>
