<?php
// auto-generated by sfPropelAdmin
// date: 2007/02/16 11:42:06
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>


<div id="sf_admin_header">
<?php include_partial('relCalendariovacunacionAlumno/edit_header', array('rel_calendariovacunacion_alumno' => $rel_calendariovacunacion_alumno)) ?>
</div>

<div id="sf_admin_container">

<?php if ($sf_request->hasErrors()): ?>
<div class="form-errors">
<h2><?php echo __('There are some errors that prevent the form to validate') ?></h2>
<ul>
<?php foreach ($sf_request->getErrorNames() as $name): ?>
  <li><?php echo $sf_request->getError($name) ?></li>
<?php endforeach; ?>
</ul>
</div>
<?php elseif ($sf_user->hasFlash('notice')): ?>
<div class="save-ok">
<h2><?php echo __($sf_user->getFlash('notice')) ?></h2>
</div>
<?php endif; ?>

<?php echo form_tag('relCalendariovacunacionAlumno/edit', 'id=sf_admin_edit_form name=sf_admin_edit_form multipart=true') ?>

<?php echo object_input_hidden_tag($rel_calendariovacunacion_alumno, 'getId') ?>


<?php
	if(!$rel_calendariovacunacion_alumno->getFkAlumnoId()) {
?>
<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('rel_calendariovacunacion_alumno[fk_alumno_id]', __('Alumno:'), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('rel_calendariovacunacion_alumno{fk_alumno_id}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('rel_calendariovacunacion_alumno{fk_alumno_id}')): ?>
    <?php echo form_error('rel_calendariovacunacion_alumno{fk_alumno_id}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php echo object_select_tag($rel_calendariovacunacion_alumno, 'getFkAlumnoId', array (
  'related_class' => 'Alumno',
  'control_name' => 'rel_calendariovacunacion_alumno[fk_alumno_id]',
)) ?>
    </div>
</div>

<?php
	} else {
		echo object_input_hidden_tag($rel_calendariovacunacion_alumno,'getFkAlumnoId',array('control_name' =>'rel_calendariovacunacion_alumno[fk_alumno_id]'));
	}
?>



<div class="form-row">
  <?php echo label_for('rel_calendariovacunacion_alumno[fk_calendariovacunacion_id]', __('Vacuna:'), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('rel_calendariovacunacion_alumno{fk_calendariovacunacion_id}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('rel_calendariovacunacion_alumno{fk_calendariovacunacion_id}')): ?>
    <?php echo form_error('rel_calendariovacunacion_alumno{fk_calendariovacunacion_id}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php echo object_select_tag($rel_calendariovacunacion_alumno, 'getFkCalendariovacunacionId', array (
  'related_class' => 'Calendariovacunacion',
  'control_name' => 'rel_calendariovacunacion_alumno[fk_calendariovacunacion_id]',
)) ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('rel_calendariovacunacion_alumno[observacion]', __('Observaci&oacute;n:'), '') ?>
  <div class="content<?php if ($sf_request->hasError('rel_calendariovacunacion_alumno{observacion}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('rel_calendariovacunacion_alumno{observacion}')): ?>
    <?php echo form_error('rel_calendariovacunacion_alumno{observacion}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php echo object_input_tag($rel_calendariovacunacion_alumno, 'getObservacion', array (
  'size' => 64,
  'control_name' => 'rel_calendariovacunacion_alumno[observacion]',
)) ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('rel_calendariovacunacion_alumno[comprobante]', __('Comprobante:'), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('rel_calendariovacunacion_alumno{comprobante}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('rel_calendariovacunacion_alumno{comprobante}')): ?>
    <?php echo form_error('rel_calendariovacunacion_alumno{comprobante}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php echo object_checkbox_tag($rel_calendariovacunacion_alumno, 'getComprobante', array (
  'control_name' => 'rel_calendariovacunacion_alumno[comprobante]',
)) ?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('rel_calendariovacunacion_alumno[fecha]', __('Fecha:'), '') ?>
  <div class="content<?php if ($sf_request->hasError('rel_calendariovacunacion_alumno{fecha}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('rel_calendariovacunacion_alumno{fecha}')): ?>
    <?php echo form_error('rel_calendariovacunacion_alumno{fecha}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php echo object_input_date_tag($rel_calendariovacunacion_alumno, 'getFecha', array (
  'rich' => true,
  'withtime' => true,
  'calendar_button_img' => sfConfig::get('sf_admin_web_dir').'/images/date.png',
  'control_name' => 'rel_calendariovacunacion_alumno[fecha]',
)) ?>
    </div>
</div>

</fieldset>

<?php echo include_partial('edit_actions', array('rel_calendariovacunacion_alumno' => $rel_calendariovacunacion_alumno)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($rel_calendariovacunacion_alumno->getId()): ?>
<?php echo button_to(__('delete'), 'relCalendariovacunacionAlumno/delete?id='.$rel_calendariovacunacion_alumno->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>

</div>

<div id="sf_admin_footer">
<?php include_partial('relCalendariovacunacionAlumno/edit_footer', array('rel_calendariovacunacion_alumno' => $rel_calendariovacunacion_alumno)) ?>
</div>
