Document: alba
Title: Debian alba Manual
Author: <insert document author here>
Abstract: This manual describes what alba is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/alba/alba.sgml.gz

Format: postscript
Files: /usr/share/doc/alba/alba.ps.gz

Format: text
Files: /usr/share/doc/alba/alba.text.gz

Format: HTML
Index: /usr/share/doc/alba/html/index.html
Files: /usr/share/doc/alba/html/*.html
