<?php
// auto-generated by sfPropelAdmin
// date: 2007/09/17 17:05:20
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('list'), 'turno/list?id='.$turno->getId(), array (
  'class' => 'sf_admin_action_list',
)) ?></li>

<?php if ($sf_user->isAuthenticated() && $sf_user->getAttribute('fk_ciclolectivo_id') != 0):?>
  <li><?php echo submit_tag(__('save'), array (
  'name' => 'save',
  'class' => 'sf_admin_action_save',
)) ?></li>
  <li><?php echo submit_tag(__('save and add'), array (
  'name' => 'save_and_add',
  'class' => 'sf_admin_action_save_and_add',
)) ?></li>
<?php endif;?>

</ul>
