<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<?php
// auto-generated by sfPropelAdmin
// date: 2007/07/02 12:48:13
?>
<?php echo form_tag('docente/edit', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
  'onsubmit'  => 'double_list_submit(); return true;'
)) ?>

<?php echo object_input_hidden_tag($docente, 'getId') ?>

<fieldset id="sf_fieldset_informacion_general" class="">
<h2><?php echo __('Informacion general') ?></h2>


<div class="form-row">

  <?php $value = object_input_tag($docente, 'getApellido', array (
  'size' => 64,
  'control_name' => 'docente[apellido]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

<div class="form-row">

  <?php $value = object_input_tag($docente, 'getNombre', array (
  'size' => 64,
  'control_name' => 'docente[nombre]',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>


<div class="form-row">

  <?php $value = object_admin_double_list($docente, 'getActividades', array (
  'control_name' => 'docente[actividades]',
  'through_class' => 'RelActividadDocente',
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>

</fieldset>


</form>

