<?php
// auto-generated by sfPropelAdmin
// date: 2007/05/02 13:04:37
?>
<?php use_helper('Javascript') ?>

<?php echo form_tag('relDivisionActividadDocente/edit', array(
  'id'        => 'sf_admin_edit_form',
  'name'      => 'sf_admin_edit_form',
  'multipart' => true,
)) ?>

<?php echo object_input_hidden_tag($rel_division_actividad_docente, 'getId') ?>

<fieldset id="sf_fieldset_none" class="">

<div class="form-row">
  <?php echo label_for('rel_division_actividad_docente[fk_division_id]', __($labels['rel_division_actividad_docente{fk_division_id}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('rel_division_actividad_docente{fk_division_id}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('rel_division_actividad_docente{fk_division_id}')): ?>
    <?php echo form_error('rel_division_actividad_docente{fk_division_id}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_select_tag($rel_division_actividad_docente, 'getFkDivisionId', array (
  'related_class' => 'Division',
  'control_name' => 'rel_division_actividad_docente[fk_division_id]',
  'include_blank' => true,
)); echo $value ? $value : '&nbsp;';

    echo observe_field('rel_division_actividad_docente_fk_division_id',
        array(  'update'   => 'item_actividad',
                'url'      => 'relDivisionActividadDocente/cambiarDivision',
                'with'     => "'rel_division_actividad_docente[fk_division_id]=' + value"));

?>
    </div>
</div>

<div class="form-row">
  <?php echo label_for('rel_division_actividad_docente[fk_actividad_id]', __($labels['rel_division_actividad_docente{fk_actividad_id}']), 'class="required" ') ?>
  <div class="content<?php if ($sf_request->hasError('rel_division_actividad_docente{fk_actividad_id}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('rel_division_actividad_docente{fk_actividad_id}')): ?>
    <?php echo form_error('rel_division_actividad_docente{fk_actividad_id}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

    <div id="item_actividad">
<?php include_component('relDivisionActividadDocente','porDivision',array(
        'id_division' => $rel_division_actividad_docente->getFkDivisionId(),
        'nombre' => 'rel_division_actividad_docente[fk_actividad_id]',
        'id_actividad' => $rel_division_actividad_docente->getFkActividadId(),
));
?>
    </div>

    </div>
</div>

<div class="form-row">
  <?php echo label_for('rel_division_actividad_docente[fk_docente_id]', __($labels['rel_division_actividad_docente{fk_docente_id}']), '') ?>
  <div class="content<?php if ($sf_request->hasError('rel_division_actividad_docente{fk_docente_id}')): ?> form-error<?php endif; ?>">
  <?php if ($sf_request->hasError('rel_division_actividad_docente{fk_docente_id}')): ?>
    <?php echo form_error('rel_division_actividad_docente{fk_docente_id}', array('class' => 'form-error-msg')) ?>
  <?php endif; ?>

  <?php $value = object_select_tag($rel_division_actividad_docente, 'getFkDocenteId', array (
  'related_class' => 'Docente',
  'control_name' => 'rel_division_actividad_docente[fk_docente_id]',
  'include_blank' => true,
)); echo $value ? $value : '&nbsp;' ?>
    </div>
</div>



<?php include_partial('evento/carga_evento', array('rel_division_actividad_docente' => $rel_division_actividad_docente, 'evento' => $evento)) ?>


</fieldset>

<?php include_partial('edit_actions', array('rel_division_actividad_docente' => $rel_division_actividad_docente)) ?>

</form>

<ul class="sf_admin_actions">
      <li class="float-left"><?php if ($rel_division_actividad_docente->getId()): ?>
<?php echo button_to(__('delete'), 'relDivisionActividadDocente/delete?id='.$rel_division_actividad_docente->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
  'class' => 'sf_admin_action_delete',
)) ?><?php endif; ?>
</li>
  </ul>
