<?php
// auto-generated by sfPropelAdmin
// date: 2007/05/02 17:35:40
?>
<ul class="sf_admin_actions">
  <li><?php echo button_to(__('create'), 'relDivisionActividadDocente/create', array (
  'class' => 'sf_admin_action_create',
)) ?></li>

<li><?php echo button_to(__('exportar'), 'relDivisionActividadDocente/exportToIcal', array (
  'class' => '',
)) ?></li>

<li><?php echo button_to(__('ver calendario'), 'relDivisionActividadDocente/verCalendario', array (
  'class' => '',
)) ?></li>

</ul>
