<?php
// auto-generated by sfPropelAdmin
// date: 2007/05/02 17:35:40
?>
<td colspan="3">
    <?php echo $rel_division_actividad_docente->getDivision() ?>
     - 
    <?php echo $rel_division_actividad_docente->getActividad() ?>
     - 
    <?php echo $rel_division_actividad_docente->getDocente() ?>
     - 
</td>