<?php
// auto-generated by sfPropelAdmin
// date: 2007/05/02 17:35:40
?>
  <th id="sf_admin_list_th_division">
        <?php echo __('Division') ?>
          </th>
  <th id="sf_admin_list_th_actividad">
        <?php echo __('Actividad') ?>
          </th>
  <th id="sf_admin_list_th_docente">
        <?php echo __('Docente') ?>
          </th>

  <th id="sf_admin_list_th_evento">
        <?php echo __('Evento') ?>
      </th>

