<?php
// auto-generated by sfPropelAdmin
// date: 2007/05/02 17:35:40
?>
<?php if ($sf_request->getError('delete')): ?>
<div class="form-errors">
  <h2>Could not delete the selected Rel division actividad docente</h2>
  <ul>
    <li><?php echo $sf_request->getError('delete') ?></li>
  </ul>
</div>
<?php endif; ?>
