<?php
// auto-generated by sfPropelAdmin
// date: 2007/05/02 17:35:40
?>
<td>
<ul class="sf_admin_td_actions">
  <li><?php echo link_to(image_tag('/sf/sf_admin/images/edit_icon.png', array('alt' => __('edit'), 'title' => __('edit'))), 'relDivisionActividadDocente/edit?id='.$rel_division_actividad_docente->getId()) ?></li>
  <li><?php echo link_to(image_tag('/sf/sf_admin/images/delete_icon.png', array('alt' => __('delete'), 'title' => __('delete'))), 'relDivisionActividadDocente/delete?id='.$rel_division_actividad_docente->getId(), array (
  'post' => true,
  'confirm' => __('Are you sure?'),
)) ?></li>
</ul>
</td>
