<?php
// auto-generated by sfPropelAdmin
// date: 2007/05/02 13:04:37
?>
<?php use_helper('Object', 'Validation', 'ObjectAdmin', 'I18N', 'Date') ?>

<?php use_stylesheet('/sf/sf_admin/css/main') ?>

<div id="sf_admin_container">

<h1><?php echo __('Editar horarios', 
array()) ?></h1>

<div id="sf_admin_header">
<?php include_partial('relDivisionActividadDocente/edit_header', array('rel_division_actividad_docente' => $rel_division_actividad_docente)) ?>
</div>

<div id="sf_admin_content">
<?php include_partial('relDivisionActividadDocente/edit_messages', array('rel_division_actividad_docente' => $rel_division_actividad_docente, 'labels' => $labels)) ?>
<?php include_partial('relDivisionActividadDocente/edit_form', array('rel_division_actividad_docente' => $rel_division_actividad_docente, 'labels' => $labels, 'evento' => $evento)) ?>
</div>

<div id="sf_admin_footer">
<?php include_partial('relDivisionActividadDocente/edit_footer', array('rel_division_actividad_docente' => $rel_division_actividad_docente)) ?>
</div>

</div>
